---
title: "Hope Valley Health Care Association"
output:
  html_document:
    df_print: paged
---

```{r}
library(Benchmarking)
```

```{r}
input <- matrix(c(150,400,320,520,350,320, 0.2, 0.7, 1.2, 2.0, 1.2, 0.7),ncol = 2)
output <- matrix(c(14000,14000,42000,28000,19000, 14000, 3500,21000,10500,42000,25000,15000), ncol= 2)

colnames(input) <- c("Staff Hours Per Day", "Supplies Per Day")
colnames(output) <- c("Reimbursed Patient-Days", "Privately Paid Patient-Days")
```

1. Perform DEA analysis by under all DEA assumptions of FDH, CRS, VRS, IRS, DRS, and FRH.
2. Determine the Peers and Lambdas under each of the above assumptions
3. Summarize your results in a tabular format.
4. If possible, plot the frontier function for each part 

## CRS
```{r}
crs <- dea(input, output, RTS = "crs")
crs
peers(crs)
lambda(crs)
```


```{r}
dea.plot(input, output, RTS = "crs")
```

## FDH

```{r}
fdh <- dea(input, output, RTS = "fdh") 
fdh

peers(fdh)
lambda(fdh)
```

```{r}
dea.plot(input, output, RTS = "fdh")
```

## VRS

```{r}
vrs <- dea(input, output,RTS = "vrs")
vrs

peers(vrs)
lambda(vrs)
```

```{r}
dea.plot(input, output, RTS = "vrs")
```

#DRS

```{r}
drs <- dea(input, output, RTS = "drs")
drs

peers(drs)
lambda(drs)
```

```{r}
dea.plot(input, output, RTS = "drs")
```


#IRS

```{r}
irs <- dea(input, output, RTS = "irs")
irs

peers(irs)
lambda(irs)
```


```{r}
dea.plot(input, output, RTS = "irs")
```

#FRH or FDH+

```{r}
fdh <- dea(input, output, RTS = "fdh+")
fdh

peers(fdh)
lambda(fdh)
```

```{r}
dea.plot(input, output, RTS = "fdh+")
```

